### PR TITLE
Stop commiting __pycache__

### PR DESCRIPTION
**Pull request by ChachyDev**

### CODE REVIEW

**Comment by proudmuslim** [comment]
I added it to .gitignore but committed it by accident beforehand so now it's sitting there

**Comment by ChachyDev** [comment]
what?

**Comment by proudmuslim** [comment]
Pycache is in gitignore

**Comment by proudmuslim** [comment]
Unless it was screwed up

**Comment by ChachyDev** [comment]
yes but the files are still there

**Comment by ChachyDev** [comment]
which this commit deletes them lol

**Comment by proudmuslim** [comment]
Yes I can remove them later

**Comment by proudmuslim** [comment]
soon:tm:

**Comment by ChachyDev** [comment]
mk

**Pull request closed without merging**
